// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kipikyuojunnmbrztiir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcGlreXVvanVubm1icnp0aWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjI3NzUsImV4cCI6MjA2NjQzODc3NX0.7q-MBdTAhzQRCxdaG4awSalh-qLZ4giZtc-Q3NV9bsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);